### ISSUE TITLE
Empty message headers due to ByteArrayLongString

### ISSUE THREAD

**Issue by aiionx** [ppat/storm-rabbitmq#31] opened 2015-09-11 06:22 UTC
In class
`RabbitMQMessageScheme`

In function
`private Map<String, Object> serialiazableHeaders(Map<String, Object> headers)`

The values are instances of
`com.rabbitmq.client.impl.LongStringHelper$ByteArrayLongString`

I expect them to be
`String`

As a result, after looping with the `instanceof` the serializableHeaders comes as empty Map.

My only rabbit dependency is:
        <dependency>
            <groupId>io.latent</groupId>
            <artifactId>storm-rabbitmq</artifactId>
            <version>0.6.0</version>
        </dependency>

**Comment by aiionx** [comment] 2015-09-11 06:55
I had to extend a local RabbitMQMessageScheme for my needs that patches that.

It only works in case the headers are strings.

Can't figure out the root cause yet.


```java
public class RabbitMQMessageScheme2 extends RabbitMQMessageScheme {

    public RabbitMQMessageScheme2(Scheme payloadScheme, String envelopeFieldName, String propertiesFieldName) {
        super(payloadScheme, envelopeFieldName, propertiesFieldName);
    }

    @Override
    public List<Object> deserialize(Message message) {
        List<Object> values = super.deserialize(message);
        Properties p = (Properties) values.get(values.size() - 1);
        setHeaders(message, p);
        return values;
    }

    private void setHeaders(Message m, Properties p){
        Message.DeliveredMessage dm = (Message.DeliveredMessage)m;
        p.getHeaders().putAll(serialiazableHeaders(dm.getHeaders()));
    }

    private Map<String, Object> serialiazableHeaders(Map<String, Object> headers) {
        if (headers == null) {
            return new HashMap<String, Object>();
        }
        Map<String, Object> serializableHeaders = new HashMap<String, Object>(headers.size());
        for (Map.Entry<String, Object> entry : headers.entrySet()) {
            serializableHeaders.put(entry.getKey(), entry.getValue().toString());
        }
        return serializableHeaders;
    }

}
```

**Comment by SeanTAllen** [comment] 2015-09-12 11:47
Do you have a self contained test case that demonstrates the problem?

**Comment by ppat** [comment] 2015-10-31 23:44
What you are noticing is the intended behavior for headers containing RabbitMQ's internal data types. 

`RabbitMQMessageScheme` will include standard data type (String's, Int's, etc..) values in the resulting headers. But if you are using any other data types, you will need to provide your own implementation of a `Scheme`, so your solution above is good for that. 

RabbitMQ client library uses some strange data types like `com.rabbitmq.client.impl.LongStringHelper$ByteArrayLongString` internally for RabbitMQ own headers. Your solution is good for that, so closing issue.

**Closed by ppat** 2015-10-31 23:44 UTC
